<?php

return [
    'defaults' => [
        'business_name' => env('APP_NAME', 'Automotive Service'),
        'logo' => null,
        'primary_color' => '#dc2626',
        'secondary_color' => '#0f172a',
        'currency_code' => null,
        'phone_number' => null,
        'whatsapp_number' => null,
        'email' => null,
        'address' => null,
        'google_maps_url' => null,
        'google_maps_embed_url' => null,
        'facebook_url' => null,
        'instagram_url' => null,
        'tiktok_url' => null,
        'footer_description_en' => null,
        'footer_description_ar' => null,
        'opening_hours' => null,
        'hero_heading' => null,
        'hero_description' => null,
        'hero_image' => null,
        'primary_cta_text' => null,
        'secondary_cta_text' => null,
        'show_about_section' => false,
        'about_eyebrow_en' => null,
        'about_eyebrow_ar' => null,
        'about_heading_en' => null,
        'about_heading_ar' => null,
        'about_description_en' => null,
        'about_description_ar' => null,
        'about_image' => null,
        'about_points' => [],
        'show_contact_section' => true,
        'contact_eyebrow_en' => null,
        'contact_eyebrow_ar' => null,
        'contact_heading_en' => null,
        'contact_heading_ar' => null,
        'contact_description_en' => null,
        'contact_description_ar' => null,
        'seo_title_en' => null,
        'seo_title_ar' => null,
        'seo_description_en' => null,
        'seo_description_ar' => null,
    ],
];
